name=epd-ite8951-gdep133ut3-esp32s3-driver
version=1.0.0
author=JustKovalchuk
maintainer=JustKovalchuk
sentence=C++ E-Ink driver for GDEP133UT3 (GoodDisplay, 13.3", 1600x1200) & IT8951 (DEJA-TC103) controller on ESP32-S3.
paragraph=Supports PSRAM framebuffering, full 16-level grayscale, fast partial updates, and on-the-fly TrueType (TTF) font rendering via LittleFS. Requires PSRAM.
category=Display
url=https://github.com/JustKovalchuk/epd-ite8951-gdep133ut3-esp32s3-driver.git
architectures=esp32
includes=IT8951.h
